server:
  port: 9999

spring:
  #  main:
  #    banner-mode: 'OFF'
  profiles:
    active:
      - dev

logging:
  level:
    ROOT: INFO
#    org.springframework.orm.jpa: DEBUG
#    org.springframework.transaction: DEBUG
---

spring:
  profiles: dev
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
#        generate_statistics: true
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/testdb
    username: test
    password: test

